name: Lint, Format , Unit-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install Dependencies
      run: |
        pipenv install
    - name: Lint python code
      run: |
        flake8 $(git ls-files '*.py')