name: Lint, Format , Unit-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}
    - name: python
      uses: actions/setup-python@main
      with:
        # pulls latest version of python, alternatively specify exact version (i.e. 3.8 -> no quotes)
        python-version: '3.10'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install Dependencies
      run: |
        pipenv install
    #- name: Lint python code
    #  run: |
    #    pipenv run lint
    #- name: Format python code
    #  run: |
    #    pipenv run format
    - name: Run tests
      run: |
        pipenv run tests